apiVersion: v1
kind: Secret
metadata:
  name: bayandigital-secrets
  namespace: bayandigital
type: Opaque
stringData:
  APP_KEY: "base64:generated-will-be-replaced"
  DB_ROOT_PASS: "rootpass123"
  DB_PASS: "bayandigital_dev_pass"
