apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bayandigital-mariadb-data
  namespace: bayandigital
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
