apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bayandigital
  namespace: bayandigital
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bayandigital.rarecreation.xyz
      secretName: bayandigital-tls
  rules:
    - host: bayandigital.rarecreation.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bayandigital
                port:
                  number: 80
